### ISSUE TITLE
Pre commit hook

### ISSUE THREAD

**Issue by amartinn** [MK-IT/utils-notion-slack-integration#7]
Implement pre commit hook, that checks for github issue id in the commit message.

**Comment by SMerdzhanov** [comment]
You can checkout the `.husky` hooks built into https://github.com/MK-IT/gatsby-starter-essentials.

We're generally looking for pre-commit, commit-msg, and pre-push hooks.

Pre-commit
- format
- lint

Commit-msg
- conventional commits

Pre-push
- test (not available right now)
- build
